
name: "build-web"

on:
  push:
    branches: [ master ]

env:
  GODOT_VERSION: 3.3.2
  EXPORT_NAME: Existence

jobs:
  export-web:
    name: Web Export 🌐
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.3.2
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup 💻
        working-directory: game
        run: |
          mkdir -v -p build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build 🔧
        working-directory: game
        run: godot -v --export "HTML5" ./build/web/index.html
      - name: Install rsync 📚
        working-directory: game
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: game/build/web # The folder the action should deploy.
          TARGET_FOLDER: early_access